#
# Copyright (c) 2000-2006 Андрей Валяев (dron@infosec.ru)
# All rights reserved.
#
# Created: 20/10/06 11:36:37
#

.SUFFIXES:

OBJECTS = $(notdir $(UNITS:.c=.o))

all:  $(TARGET)

$(TARGET) : $(OBJECTS)
	$(ECHO) Create library $@...
	$(MKDIR) -p $(dir $@)
	$(AR) -r $@ $(OBJECTS)
	$(RANLIB) $@

