#!/usr/bin/perl -w
#
# Copyright (c) 2000-2005 Andrey Valyaev (dron@infosec.ru)
# All rights reserved.
#

use lib $ENV{'MDF_REPOS'} . '/Script';

use strict;

use MDF::Hash;

foreach (@ARGV) {
	print MDF::Hash->File ("", $_), "\n";
}
