katetemplate: Template=Makefile Group=MDF Highlight=&Makefile
katetemplate: Author=Andrey Valyaev (dron@infosec.ru)
#
# Copyright (c) 2000-%{year} %{fullname} <%{email}>
# This code is licenced under the GPL3 (http://www.gnu.org/licenses/#GPL)
#

all:
